### PR TITLE
Truncate names that are longer than 64 characters

### LINKED ISSUE #9: 'roleName' failed to satisfy constraint: Member must have length less than or equal to 64
serverless.yml:
```
plugins:
  - serverless-dynamodb-autoscaling

custom:
  capacities:
    - table: subscriptionsTable
      index:
        - SubscriptionsUserIdIndex
      read:
        minimum: 1
        maximum: 100
        usage: 0.7
      write:
        minimum: 1
        maximum: 100
        usage: 0.7
```

output:
```
  Serverless Error ---------------------------------------

  An error occurred while provisioning your stack: DynamoDBAutoscaleRolesubscriptionsTableSubscriptionsUserIdIndexdev - 1 validation error detected: Value 'DynamoDBAutoscaleRolesubscriptionsTableSubscriptionsUserIdIndexdev' at 'roleName' failed to satisfy constraint: Member must have length less than or equal to 64.
```

I think the error is indicating the role name must be <=64 characters. When the role name is generated, is there a way to shorten it? Or use the existing `DynamoDBAutoscaleRole`?

### PR DESCRIPTION
**Pull request by sbstjn**
This should fix #9 

If the name is longer than 64 characters, I use a `md5` hash instead.

### CODE REVIEW

File: src/aws/names.js [hunk 1]
```diff
@@ -1,7 +1,12 @@
 const util = require('util')
+const md5 = require('md5')
 
 function clean (input) {
-  return input.replace(/[^a-z0-9+]+/gi, '')
+  return turncate(input.replace(/[^a-z0-9+]+/gi, ''))
+}
+
+function turncate (input) {
```
Comment (charleswhchan) [inline src/aws/names.js]: typo: truncate

File: src/aws/names.js [hunk 2]
```diff
@@ -1,7 +1,12 @@
...
+  return input.length > 64 ? md5(input) : input
```
Comment (charleswhchan) [inline src/aws/names.js]: Suggestion: since `md5()` functions returns a hex string (length = 128 bit / 4 bit = 32 characters), and the roleName can be up to 64 characters long, would it be useful to generate a roleName by taking the first 32 characters from the original role name + 32 characters from the hex string? 

This helps provide a bit of context when there are lots of looking through the list of Roles in IAM within the account when there are potentially lots of serverless deployments.

Just a thought. 😃

**Comment by sbstjn** [comment]
I agree, that should be the final solution. Maybe I can fix this later
tonight. Thanks for noticing my typos over and over ;)

**Comment by sbstjn** [comment]
Released as `v0.3.2`

**Comment by charleswhchan** [comment]
Thank you!
